apiVersion: apps/v1
kind: Deployment
metadata:
  name: osint-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: osint-frontend
  template:
    metadata:
      labels:
        app: osint-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/ibrahimkhalilmasud/osint-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: osint-frontend
spec:
  selector:
    app: osint-frontend
  ports:
    - port: 3000
      targetPort: 3000
